project_name: go-swap-server
builds:
- main: ./cmd/server/.
  binary: go-swap-server
  ldflags:
  - -s -w -X main.build={{.Version}}
  env:
  - CGO_ENABLED=0

archive:
  replacements:
    windows: Windows
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
