language: go

go:
- 1.x
- '1.8'
- 1.10.x
- 1.11.x
- master

services:
- docker

env:
  global:
  - secure: 2I0+pzIvKKi9RbmAjOBCS4gQFf7+KTDLIcGpoTPsvMUG6XMRiv5WUV0GWGRtKEpBs/iHOEOL2OkCI1SsN/mMyK/HcRLyotVDht12KILhmQxc5+ApawcaoU0LM4pnMthOztm3y+jX58F8NBqksLt3JCSinLr4eX/wTjsaJnjnGjncACFEiXUZK2566rFoTpJZR+UOCvhGGK6Nq8OWgh4K3OHAIeJB7xjGI8R3YTHkWtqhgQZAmMCbjxQHASqbfgYAFrMwvajnHWUpKtULLt1h4h6VDKoCE7yWyTGiF/8jQ4jDswlwfkRKZhG08AFtQQWf0ow3ojuZzz2SnmzV31zK73hLTuDHBCr3tjMAV69ErdK15FAvgCdlfQS1/MCNOsVcYRhpsNV79Qt644oS7yOh4uJglh9bx49cd1BiEremzsbxNK2MA2s6RmW0dG2ROYeHNXpcowPJIfuKFdHtDhTyza8qLQEiFAGYG64lJ87Hm4SYOT59aoAT7l3wSM+U9uTC8+PS/OyBTfanFe8jJ5L9OVL6v6SRzhLOPxrgcjSCn9HkUIzpRMlxnY4RMFVQ/tdpLl5s/9GRoEk2P3gimIgNlkzid6EzJ3XfcOmxm95RMbH2bBAg4a8qegFT4Q1+j2NnJ4f3AW8e20LQ3x4lPjz+MYtIdLeXLemiIEo2UECsTWU=
  - secure: fVf1QTPl1+RWTLO1SCSGglXIgzhQVKBGRqNovE2vJRIxCNqV+qYTXXw/LG3OC3KxMYoyOtV26RTM6CpRqb8ZDn3+1UTi2XRJqtad+CKpPxLn6aWd3wy2lo+FmzAFeHS80LtH/kDumY7joBY6uDQht2buN7k48ZOmydVfQjWxvWfic6AhgjSaAOPWCvVyMiyVRxBeANRzq3Cn63756zgkHTEKndY1t2tskLlKFZYXu0Omx0FTc9hBEIl1aU6U3TKV0Rnn5i7NN6ezTLW9oqAOJUAha/Z8E06a1SO+GDR0bgmgRySOBFgJXaDuYRgyH5sDTzvFZYTCZSagfcAmPWavT3zoW/6X2BVGRCF46FbW9vfviZcQnoIkkHo6cS5DwFm9nH0hFV3T1ygGwdf5kVqPYZbEfoxzV5L3CGsBa5KM+ujugjPp60Fsg+Q5MhxmFlgk9f/39RdU7wvmZWrfL17mIc4S5Np/0FwRcbHHbJrXnC3RG5cWG39QPzeiyyWFyA8+1NkgkfP+EHvyTCfxo8wTqplfD0mYAoPAvzbWv4QZRXSjnxdhyKGJ/poMNkSK6FGomIXipd6C2i1VbBu8YkeOTS3kadwBtZtrZG+Z0g+2WibkoHcKIG/0HM67qMSaHEdvW9qsMSdIUR8c9YPlcVy/4FQs6WDc8ybmwTGH1lpFIfg=

jobs:
  include:

  - stage: test
    script:
    - make test-docker

  - stage: build
    script:
    - make build
    - test -f bin/linux-amd64/server
    - make container
    - docker images | grep me-io/go-swap-server-linux-amd64

  - stage: docker
    script:
    - "./scripts/build-docker.sh"

