language: go
go:
- "1.x"
- "1.8"
- "1.10.x"
- "1.11.x"
- master

services:
- docker

script:
- make test-docker
- make build
- test -f bin/linux-amd64/swap-server
- make container
- docker images | grep me-io/swap-server-linux-amd64
#after_success:
#- bash <(curl -s https://codecov.io/bash)
#
